### ISSUE TITLE
「シンプルな例」から「PHPUnitとの統合」へのページリンク切れが起きている

### ISSUE THREAD

**Issue by denvernine** [HiroKws/mockery-japanese-docs#3]
「シンプルな例」から「PHPUnitとの統合」に対するリンクがページ最下部にありますが、日本語と英語の両方でリンク切れが起きていました。

## 日本語

再現頻度: 常に
検証環境:
- Firefix Developer Edition 115.0b9 (64-bit)
- Google Chrome Version 116.0.5845.14 (Official Build) dev (64-bit)

起きていること:
[シンプルな例:Mockery1.0](https://readouble.com/mockery/1.0/ja/simple_example.html) から [PHPUnitとの統合:Mockery1.0](https://readouble.com/mockery/1.0/ja/phpunit_integration.html) に対してのリンクが切れている。リンク先URLが `https://readouble.com/mockery/1.0/ja/phpunit_integration` になっており、末尾の `.html` が抜けている。

## English

再現頻度: 常に
検証環境:
- Firefix Developer Edition 115.0b9 (64-bit)
- Google Chrome Version 116.0.5845.14 (Official Build) dev (64-bit)

起きていること:
[Simple Example:Mockery1.0](https://readouble.com/mockery/1.0/en/simple_example.html) から [PHPUnit Integration:Mockery1.0](https://readouble.com/mockery/1.0/en/phpunit_integration.html) に対してのリンクが "/reference/phpunit_integration" という文字列になっている。

ref: https://github.com/mockery/mockery/blob/main/docs/getting_started/simple_example.rst

**Comment by HiroKws** [comment]
和文はリンクを手作業で書き換えていますが、英語は和文の参考の位置づけで、英文が必要な人はオリジナルのドキュメントを見るでしょうから、リンクは当初から外れたままです。書き直していません。（次回、作り直すときに、サクセス数などを考慮して、対応するかどうかを決めたいと思います。）和文のリンクに関しては、そもそもサーバーの設定で.htmlなくても.htmlファイルへアクセスするようにしていたものが、Laravel Forgeに設定を任せた時点で、その設定がされていませんでした。サーバーの設定を変更しました。

**Comment by denvernine** [comment]
英語ページの対応方針について承知いたしました。対応ありがとうございます。
